import type { Property } from "@/types/property";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=70`;

export const ALL_AMENITIES = [
  "Lift",
  "Power Backup",
  "Gym",
  "Swimming Pool",
  "Clubhouse",
  "24x7 Security",
  "Covered Parking",
  "Landscaped Park",
  "Gas Pipeline",
  "Children's Play Area",
  "CCTV Surveillance",
  "Wi-Fi Ready",
];

export const POPULAR_CITIES = [
  "Mumbai",
  "Bangalore",
  "Pune",
  "Gurugram",
  "Hyderabad",
  "Delhi",
];

export const properties: Property[] = [
  {
    id: "1",
    title: "Spacious 4BHK Villa with Private Garden",
    description:
      "An elegant east-facing villa in a gated community, featuring a private garden, modular kitchen, and premium Italian-marble flooring. Walking distance to top schools and tech parks. The home enjoys abundant natural light and cross-ventilation throughout the day.",
    listingType: "buy",
    propertyType: "Villa",
    price: 35000000,
    areaSqft: 3200,
    bedrooms: 4,
    bathrooms: 4,
    isFurnished: true,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    images: [
      img("1568605114967-8130f3a36994"),
      img("1570129477492-45c003edd2be"),
      img("1600585154340-be6161a56a0c"),
      img("1631679706909-1844bbd07221"),
    ],
    amenities: [
      "Swimming Pool",
      "Clubhouse",
      "24x7 Security",
      "Covered Parking",
      "Landscaped Park",
      "Gym",
    ],
    isFeatured: true,
    postedDaysAgo: 2,
    owner: { name: "Rohan Mehta", type: "Owner", phone: "+91 98xxxxxx21" },
  },
  {
    id: "2",
    title: "Modern 2BHK Apartment near Metro Station",
    description:
      "A well-maintained 2BHK in a prime location, just 400m from the metro. Comes semi-furnished with wardrobes and modular kitchen. Ideal for working professionals and small families. Society offers a gym, power backup and round-the-clock security.",
    listingType: "rent",
    propertyType: "Apartment",
    price: 65000,
    areaSqft: 1050,
    bedrooms: 2,
    bathrooms: 2,
    isFurnished: false,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    images: [
      img("1502672260266-1c1ef2d93688"),
      img("1512917774080-9991f1c4c750"),
      img("1600607687939-ce8a6c25118c"),
    ],
    amenities: ["Lift", "Power Backup", "Gym", "24x7 Security", "Covered Parking"],
    isFeatured: true,
    postedDaysAgo: 1,
    owner: { name: "Priya Nair", type: "Owner", phone: "+91 99xxxxxx08" },
  },
  {
    id: "3",
    title: "Premium 3BHK Apartment in IT Corridor",
    description:
      "Brand-new 3BHK in a RERA-approved tower, surrounded by leading IT companies. High-rise unit on the 14th floor with a panoramic city view. Includes covered parking, gas pipeline and a sprawling clubhouse with infinity pool.",
    listingType: "buy",
    propertyType: "Apartment",
    price: 9500000,
    areaSqft: 1480,
    bedrooms: 3,
    bathrooms: 3,
    isFurnished: false,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Hinjewadi",
    city: "Pune",
    state: "Maharashtra",
    images: [
      img("1545324418-cc1a3fa10c00"),
      img("1512915922686-57c11dde9b6b"),
      img("1493809842364-78817add7ffb"),
    ],
    amenities: [
      "Swimming Pool",
      "Clubhouse",
      "Gym",
      "Gas Pipeline",
      "Children's Play Area",
      "CCTV Surveillance",
    ],
    isFeatured: true,
    postedDaysAgo: 4,
    owner: { name: "Suhas Realtors", type: "Builder", phone: "+91 98xxxxxx55" },
  },
  {
    id: "4",
    title: "Independent 3BHK House with Terrace",
    description:
      "A fully furnished independent house in an upscale neighbourhood. Spacious rooms, a private terrace garden and dedicated parking for two cars. Quiet, green street close to malls, hospitals and international schools.",
    listingType: "rent",
    propertyType: "House",
    price: 85000,
    areaSqft: 2100,
    bedrooms: 3,
    bathrooms: 3,
    isFurnished: true,
    parkingAvailable: true,
    vastuCompliant: false,
    locality: "DLF Phase 3",
    city: "Gurugram",
    state: "Haryana",
    images: [
      img("1605276374104-dee2a0ed3cd6"),
      img("1600596542815-ffad4c1539a9"),
      img("1600566753190-17f0baa2a6c3"),
    ],
    amenities: ["Power Backup", "Covered Parking", "24x7 Security", "Landscaped Park"],
    isFeatured: false,
    postedDaysAgo: 6,
    owner: { name: "Anil Kapoor", type: "Agent", phone: "+91 97xxxxxx12" },
  },
  {
    id: "5",
    title: "Luxury 4BHK House in Gated Layout",
    description:
      "Contemporary 4BHK house with double-height living room, home-office space and a landscaped backyard. Located in a secure layout with parks and a community hall. Vaastu-compliant and ready to move in.",
    listingType: "buy",
    propertyType: "House",
    price: 18500000,
    areaSqft: 2750,
    bedrooms: 4,
    bathrooms: 4,
    isFurnished: false,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    images: [
      img("1580587771525-78b9dba3b914"),
      img("1564013799919-ab600027ffc6"),
      img("1600047509807-ba8f99d2cdde"),
    ],
    amenities: [
      "Clubhouse",
      "24x7 Security",
      "Covered Parking",
      "Landscaped Park",
      "Children's Play Area",
    ],
    isFeatured: true,
    postedDaysAgo: 9,
    owner: { name: "Lakshmi Reddy", type: "Owner", phone: "+91 90xxxxxx77" },
  },
  {
    id: "6",
    title: "Cozy 1BHK Apartment for Bachelors",
    description:
      "Compact and affordable 1BHK in the heart of the startup hub. Walkable to cafes, co-working spaces and pubs. Semi-furnished with a fridge, bed and wardrobe. Great for a single professional or a couple.",
    listingType: "rent",
    propertyType: "Apartment",
    price: 28000,
    areaSqft: 620,
    bedrooms: 1,
    bathrooms: 1,
    isFurnished: false,
    parkingAvailable: false,
    vastuCompliant: false,
    locality: "Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    images: [
      img("1605146769289-440113cc3d00"),
      img("1502005229762-cf1b2da7c5d6"),
      img("1586023492125-27b2c045efd7"),
    ],
    amenities: ["Lift", "Power Backup", "Wi-Fi Ready", "CCTV Surveillance"],
    isFeatured: false,
    postedDaysAgo: 3,
    owner: { name: "Karthik Rao", type: "Owner", phone: "+91 96xxxxxx34" },
  },
  {
    id: "7",
    title: "Residential Plot in Fast-Growing Suburb",
    description:
      "A clear-title, gated residential plot ready for construction. Located in a rapidly developing corridor with wide internal roads, underground drainage and a proposed ring-road connection. Solid long-term investment.",
    listingType: "buy",
    propertyType: "Plot",
    price: 5500000,
    areaSqft: 2400,
    bedrooms: 0,
    bathrooms: 0,
    isFurnished: false,
    parkingAvailable: false,
    vastuCompliant: true,
    locality: "Wagholi",
    city: "Pune",
    state: "Maharashtra",
    images: [
      img("1502082553048-f009c37129b9"),
      img("1486406146926-c627a92ad1ab"),
    ],
    amenities: ["24x7 Security", "Landscaped Park"],
    isFeatured: false,
    postedDaysAgo: 14,
    owner: { name: "Greenfield Estates", type: "Builder", phone: "+91 95xxxxxx90" },
  },
  {
    id: "8",
    title: "Premium Office Space in Business District",
    description:
      "A Grade-A commercial office on a high-visibility floor, ideal for corporate headquarters. Fully air-conditioned with dedicated parking, high-speed lifts and 100% power backup. Surrounded by banks, hotels and metro connectivity.",
    listingType: "rent",
    propertyType: "Commercial",
    price: 250000,
    areaSqft: 3500,
    bedrooms: 0,
    bathrooms: 2,
    isFurnished: true,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Bandra Kurla Complex",
    city: "Mumbai",
    state: "Maharashtra",
    images: [
      img("1497366754035-f200968a6e72"),
      img("1497366811353-6870744d04b2"),
    ],
    amenities: ["Lift", "Power Backup", "24x7 Security", "Covered Parking", "CCTV Surveillance"],
    isFeatured: false,
    postedDaysAgo: 5,
    owner: { name: "Metro Commercial LLP", type: "Agent", phone: "+91 93xxxxxx41" },
  },
  {
    id: "9",
    title: "Well-Lit 3BHK Apartment with Park View",
    description:
      "A sunny 3BHK facing a central park, in a well-established society. Recently repainted with new modular kitchen fittings. Excellent connectivity to the airport and expressway. Family-friendly community with ample green space.",
    listingType: "buy",
    propertyType: "Apartment",
    price: 12500000,
    areaSqft: 1620,
    bedrooms: 3,
    bathrooms: 2,
    isFurnished: false,
    parkingAvailable: true,
    vastuCompliant: true,
    locality: "Dwarka",
    city: "Delhi",
    state: "Delhi",
    images: [
      img("1600585154340-be6161a56a0c"),
      img("1600607687939-ce8a6c25118c"),
      img("1600566753190-17f0baa2a6c3"),
    ],
    amenities: [
      "Lift",
      "Power Backup",
      "Gym",
      "Landscaped Park",
      "Children's Play Area",
      "24x7 Security",
    ],
    isFeatured: true,
    postedDaysAgo: 7,
    owner: { name: "Meera Sharma", type: "Owner", phone: "+91 98xxxxxx63" },
  },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.isFeatured);
}

export function getSimilarProperties(property: Property): Property[] {
  return properties
    .filter((p) => p.id !== property.id && p.city === property.city)
    .slice(0, 3);
}
